#' Load and Clean Patient Registry Data
#'
#' This script loads patient registry data from a Stata `.dta` file, removes unnecessary columns, 
#' and returns a cleaned dataset for further analysis.
#'
#' The columns to remove are categorized into multiple lists (`columns_to_remove1` to `columns_to_remove8`) 
#' to improve organization and maintainability.
#'
#' @param file_path A string specifying the file path to the `.dta` dataset.
#'
#' @return A cleaned data frame with unnecessary columns removed.
#'
#' @details
#' - The function **loads the dataset using `read_dta()`** (from the `haven` package).
#' - A **list of columns to remove** is pre-defined and combined before filtering.
#' - Uses **`dplyr::select(-all_of(columns_to_remove))`** to remove unwanted columns efficiently.
#'
columns_to_remove1 <- c("quest", "bemerkungenbase", "op_infoprogramm", "emailvalid", "anothreg", "anothreg_list___1", "anothreg_list___2", "anothreg_study___1", "anothreg_study___2", "anothreg_study___3", "anothreg_reg___1", "anothreg_reg___2", "anothreg_reg___3", "anothreg_pid1_03", "anothreg_pid1_04", "anothreg_pid1_05", "anothreg_pid1_06", "anothreg_pid1_07", "anothreg_pid1_08", "anothreg_pid1_09", "anothreg_pid1_10", "anothreg_pid1_11", "anothreg_pid1_12", "anothreg_pid1_13", "anothreg_pid1_14", "anothreg_pid1_15", "anothreg_pid1_16", "anothreg_pid1_17", "anothreg_pid1_18", "anothreg_pid1_19", "anothreg_pid1_20", "ausschluss", "fm2jdatdef", "fm5jdatdef", "fm10jdatdef", "examyn___1", "examynco___1", "examynrx___1", "examnreasdesc", "promyn___1", "promynco___1", "promnreas", "promnreasdesc", "sgopyn___1", "sgopynco___1", "sgopynrx___1", "sgoplot_touch___1", "bemerkung")

columns_to_remove2 <- c("monitoring_complete", "pid_check", "imxrintaktartpost1", "imxrintaktartpost2", "imxrintaktartpost3", "imxrintaktbrpost", "imxrintaktentpost", "imxrmigratkopost", "imxrperiverkalklokpost1", "imxrperiverkalklokpost2", "imxrperiverkalklokpost3", "imxrperiverkalklokpost4", "exambem", "sgeintrdt", "sgaustrdt", "sgimpgr", "sgimpprox", "sgimpdist1", "sgimpdist2", "sgimpdist3", "sgtouchpf_typ", "sgtouchpf", "sgtouchlotpfanne", "sgtouchhals", "sgtouchhalsger", "sgtouchhals15", "sgtouchlothals", "sgtouchschaft", "sgtouchlotschaft_", "sgpyrocloc", "sgpyroc", "sgimplout", "sgimploutteil___1", "sgimploutteil___2", "sgimploutteil___3", "sgimploutteil___4", "sgimploutteiltouch___1", "sgimploutteiltouch___2", "sgimploutteiltouch___3", "sgimploutteiltouch___4", "sgimploutoth", "sgimplin", "sgimplinkomp", "sgimpinprox", "sgimpindist4", "sgimpinhigh", "sgtouchinpf_typ", "sgtouchinpf", "sgtouchpfinplot", "sgtouchinhals", "sgtouchinhalsger", "sgtouchinhals15", "sgtouchinhalslot", "sgtouchinhalslot", "sgtouchinschaft", "sgtouchinschaftlot", "sgpyrocinloc", "sgpyrocin", "sgothimplin", "sgopzugang", "sgopkapsel", "sgopspaltung", "sgonedate", "sgoperateurtxt", "sgdateimp", "sgoperateurimp", "sgoperateurtxtimp", "sgopothimp", "sgopothtxtimp", "sgeintrdtimp", "sgaustrdtimp", "sgopdauerimp", "mhdiagnose_rev", "mhdiagrevtxt", "imxraphynex", "imxraptynex", "imxraptlatex", "imxrdtex")

columns_to_remove3 <- c("imxraxeex", "imxrzystenbex", "imxrzystenblokex1", "imxrzystenblokex2", "imxrzystenblokex3", "imxrzystenblokex4", "imxraphynimp", "imxraptynimp", "imxraptlatimp", "imxrdtimp", "imxraxeimp", "imxrzystenbimp", "imxrzystenblokimp1", "imxrzystenblokimp2", "imxrzystenblokimp3", "imxrzystenblokimp4", "guestdoc", "guestdoc_nr", "sgopdt_status_cdp", "returnwork", "returnworknot", "returnworkdays", "returnwork_en", "returnworknot_en", "returnworkdays_en", "returnwork_fr", "returnworknot_fr", "returnworkdays_fr", "returnwork_it", "returnworknot_it", "returnworkdays_it","therapy", "therapyongoing", "therapy_en", "therapyongoing_en", "therapy_fr", "therapyongoing_fr", "therapy_it", "therapyongoing_it", "aegen___1", "aegen___2", "aegen___3", "aegen___99", "aegenothtxt", "aeplocgen", "aeplocimp___1", "aeplocimp___2", "aeplocimp___3", "aeplocimp___4", "aeplocimp___5", "aeplocimp___6", "aeplocimp___7", "aeplocimp___8", "aeplocimp___9", "aeplocimp___10", "aeplocimp___11", "aeplocimp___12", "aeplocimp___13", "aeplocimp___14", "aeplocimp___15", "aeplocimp___16", "aeplocimp___17", "aeplocimp___18", "aeplocimp___99", "aeplocimp_text", "aegensyst___1", "aegensyst___2", "aegensyst___3", "aegensyst___4", "aegensyst___5", "aegensyst___6", "aegensyst___7", "aegensyst___8", "aegensyst___9", "aegensyst___10")

columns_to_remove4 <- c("aegensyst_descr", "aetreat", "aetreatoption___1", "aetreatoption___2", "aetreatoption___3", "aetreatoption___4", "aetreatoption___5", "aetreatoption___6", "aetreatoption___7", "aetreatoption___8", "aetreatoption___9", "aetreatoption___10", "aetreatoption___11", "aetreatoption___99", "aetreatdat1", "aetreatdesc1", "aetreatdat2", "aetreatdesc2", "aetreatdat3", "aetreatdesc3", "aeoutcome", "aestpm", "aestdescpm", "aepicture", "adverse_event_complete", "ae", "examtime", "examtimeM", "examtimeW6w", "examtimeM3m", "examtimeM24m", "examtimeY12m", "examtimeY24m", "examtimeY5y", "examtimeY10y", "promtiming", "promtime", "promtimeM", "promtimeW6w", "promtimeM3m", "promtimeM24m", "promtimeY12m", "promtimeY24m", "promtimeY5y", "promtimeY10y", "plannedfudt", "daystofu", "fuptodonow", "prommonth", "dup", "futime", "futimeM", "futimeY", "AgeExamc", "sgoperateurimp2", "klinauf", "bmhq_miss_en", "bmhq_miss_fr", "bmhq_miss_it", "bmhq_miss", "bmhqmiss_mean", "eq5d5l_miss", "eq5d5l_miss_en", "eq5d5l_miss_fr", "eq5d5l_miss_it", "mhside_en", "mhside_fr", "mhside_it", "promdt_en", "promdt_it", "promdt_fr", "domhand_en", "domhand_fr", "domhand_it", "beruf_en", "beruf_fr", "beruf_it", "erwartreason_en", "erwartreason_fr", "erwartreason_it", "erwarterfuell_en", "erwarterfuell_fr", "erwarterfuell_it", "erwartausmass_en", "erwartausmass_fr", "erwartausmass_it", "anchorforce_en", "anchorforce_fr", "anchorforce_it", "zufried_en", "zufried_fr", "zufried_it", "opagain_en", "opagain_fr", "opagain_it")

columns_to_remove5 <- c("language", "anothreg_pid1_01", "anothreg_pid1_02", "revis", "revlastnk", "revisdigfid", "revisdigregid", "dropteilklreas", "dropteilklreasoth", "dropoutreas", "dropoutreasdesc", "dropoutreasoth", "dropoutdeath", "dropoutdeath", "fm6wodatdef", "fm3modatdef", "fm1jdatdef", "fmopdatum", "examndreas", "aeclinpost", "aeclintxtpost", "imxraphynpost", "imxraptynpost", "imxraptlatpost", "imxrnonepost", "imxrnonereapost", "imxrintaktpost", "imxrmigratpost", "imxrmigrattouchpost", "imxrmigratlokpost1", "imxrmigratlokpost2", "imxrmigratlokpost3", "imxrmigratlokpost4", "imxrsaumbpost", "imxrsaumblokpost1", "imxrsaumblokpost2", "imxrstressfxpost", "imxrstressfxlokpost1", "imxrstressfxlokpost2", "imxrzystenbpost", "imxrzystenblokpost1", "imxrzystenblokpost2", "imxrzystenblokpost3", "imxrzystenblokpost4", "imxrbonereapost", "imxrbonereapost1", "imxrbonereapost2", "imxrbonereapost3", "imxrbonereapost4", "imxrbonereatxtpost", "imxrperiverkalkpost", "flexmcp", "nullstmcp", "extmcp", "flexip", "nullstip", "extip", "pid_check_op", "surgery_date_check_op", "sgtreat", "sgopdauer", "imxraphynprae", "imxraptynprae", "imxraptlatprae", "imxrzystenbprae", "imxrzystenblokprae1", "imxrzystenblokprae2", "imxrzystenblokprae3", "imxrzystenblokprae4", "sgae", "sgaetxt", "sgbem", "operationsformular_complete", "cdp_complete", "transform_erwartreason", "erwartreason_domain", "erwart_now_beweg", "erwart_now_aesth", "erwart_now_alltag", "erwart_now_freizeit", "erwart_now_kraft", "erwart_now_arbeit", "erwart_now_painruhe", "erwart_now_painadl", "erwart_wunsch_beweg", "erwart_wunsch_aesth", "erwart_wunsch_alltag")

columns_to_remove6 <- c("erwart_wunsch_freizeit", "erwart_wunsch_kraft", "erwart_wunsch_arbeit", "erwart_wunsch_painruhe", "erwart_wunsch_painadl", "transform_erwartreason_en", "erwartreason_domain_en", "erwart_now_beweg_en", "erwart_now_aesth_en", "erwart_now_alltag_en", "erwart_now_freizeit_en", "erwart_now_kraft_en", "erwart_now_arbeit_en", "erwart_now_painruhe_en", "erwart_now_painadl_en", "erwart_wunsch_beweg_en", "erwart_wunsch_aesth_en", "erwart_wunsch_alltag_en", "erwart_wunsch_freizeit_en", "erwart_wunsch_kraft_en", "erwart_wunsch_arbeit_en", "erwart_wunsch_painruhe_en", "erwart_wunsch_painadl_en", "transform_erwartreason_fr", "erwartreason_domain_fr", "erwart_now_beweg_fr", "erwart_now_aesth_fr", "erwart_now_alltag_fr", "erwart_now_freizeit_fr", "erwart_now_kraft_fr", "erwart_now_arbeit_fr", "erwart_now_painruhe_fr", "erwart_now_painadl_fr", "erwart_wunsch_beweg_fr", "erwart_wunsch_aesth_fr", "erwart_wunsch_alltag_fr", "erwart_wunsch_freizeit_fr", "erwart_wunsch_kraft_fr", "erwart_wunsch_arbeit_fr", "erwart_wunsch_painruhe_fr", "erwart_wunsch_painadl_fr", "transform_erwartreason_it", "erwartreason_domain_it", "erwart_now_beweg_it", "erwart_now_aesth_it", "erwart_now_alltag_it", "erwart_now_freizeit_it", "erwart_now_kraft_it", "erwart_now_arbeit_it", "erwart_now_painruhe_it", "erwart_now_painadl_it", "erwart_wunsch_beweg_it", "erwart_wunsch_aesth_it", "erwart_wunsch_alltag_it", "erwart_wunsch_freizeit_it", "erwart_wunsch_kraft_it", "erwart_wunsch_arbeit_it", "erwart_wunsch_painruhe_it", "erwart_wunsch_painadl_it", "sane", "painruhenrs_en", "paintaetnrs_en", "sane_en", "painruhenrs_fr")

columns_to_remove7 <- c("paintaetnrs_fr", "sane_fr", "painruhenrs_it", "paintaetnrs_it", "sane_it", "ceq_1", "ceq_2", "ceq_3", "ceqp_1", "ceqp_2", "ceqp_3", "ceq_1_en", "ceq_2_en", "ceq_3_en", "ceqp_1_en", "ceqp_2_en", "ceqp_3_en", "ceq_1_fr", "ceq_2_fr", "ceq_3_fr", "ceqp_1_fr", "ceqp_2_fr", "ceqp_3_fr", "ceq_1_it", "ceq_2_it", "ceq_3_it", "ceqp_1_it", "ceqp_2_it", "ceqp_3_it", "opagain", "anchor", "erwarterfuell", "erwart_post_beweg", "erwart_post_aesth", "erwart_post_alltag", "erwart_post_freizeit", "erwart_post_kraft", "erwart_post_arbeit", "erwart_post_pain", "erwart_post_painruhe", "erwart_post_painadl", "anchorforce", "anchor_en", "erwart_post_beweg_en", "erwart_post_aesth_en", "erwart_post_alltag_en", "erwart_post_freizeit_en", "erwart_post_kraft_en", "erwart_post_arbeit_en", "erwart_post_pain_en", "erwart_post_painruhe_en", "erwart_post_painadl_en", "anchor_fr", "erwart_post_beweg_fr", "erwart_post_aesth_fr", "erwart_post_alltag_fr", "erwart_post_freizeit_fr", "erwart_post_kraft_fr", "erwart_post_arbeit_fr", "erwart_post_pain_fr", "erwart_post_painruhe_fr", "erwart_post_painadl_fr", "anchor_it", "erwart_post_beweg_it", "erwart_post_aesth_it", "erwart_post_alltag_it", "erwart_post_freizeit_it")

columns_to_remove8 <- c("erwart_post_kraft_it", "erwart_post_arbeit_it", "erwart_post_pain_it", "erwart_post_painruhe_it", "erwart_post_painadl_it", "cahps_1", "cahps_2", "cahps_3", "cahps_4", "cahps_5", "cahps_1_en", "cahps_2_en", "cahps_3_en", "cahps_4_en", "cahps_5_en", "cahps_1_fr", "cahps_2_fr", "cahps_3_fr", "cahps_4_fr", "cahps_5_fr", "cahps_1_it", "cahps_2_it", "cahps_3_it", "cahps_4_it", "cahps_5_it", "bmhq_1", "bmhq_2", "bmhq_3", "bmhq_4", "bmhq_5", "bmhq_6", "bmhq_7", "bmhq_8", "bmhq_9", "bmhq_10", "bmhq_11", "bmhq_12", "bmhq_1_en", "bmhq_2_en", "bmhq_3_en", "bmhq_4_en", "bmhq_5_en", "bmhq_6_en", "bmhq_7_en", "bmhq_8_en", "bmhq_9_en", "bmhq_10_en", "bmhq_11_en", "bmhq_12_en", "bmhq_1_fr", "bmhq_2_fr", "bmhq_3_fr", "bmhq_4_fr", "bmhq_5_fr", "bmhq_6_fr", "bmhq_7_fr", "bmhq_8_fr", "bmhq_9_fr", "bmhq_10_fr", "bmhq_11_fr", "bmhq_12_fr", "bmhq_1_it", "bmhq_2_it", "bmhq_3_it", "bmhq_4_it", "bmhq_5_it", "bmhq_6_it", "bmhq_7_it", "bmhq_8_it", "bmhq_9_it", "bmhq_10_it", "bmhq_11_it", "bmhq_12_it", "eq5d5l01_en", "eq5d5l02_en", "eq5d5l03_en", "eq5d5l04_en", "eq5d5l05_en", "eq5d5l01_fr", "eq5d5l02_fr", "eq5d5l03_fr", "eq5d5l04_fr", "eq5d5l05_fr", "eq5d5l01_it", "eq5d5l02_it", "eq5d5l03_it", "eq5d5l04_it", "eq5d5l05_it", "eq5d5lvas_en", "eq5d5lvas_fr", "eq5d5lvas_it", "aepat", "aepatdig", "aepattxt", "aepatbother", "aepat_en", "aepatdig_en", "aepattxt_en", "aepatbother_en", "aepat_fr", "aepatdig_fr", "aepattxt_fr", "aepatbother_fr", "aepat_it", "aepatdig_it", "aepattxt_it", "aepatbother_it", "fragebbem_en", "fragebbem_fr", "fragebbem_it",  "fragebbem", "aevisit1dt", "aeprepost", "examstatus", "examtiming", "examtimeM12m", "promtimeM12m", "eq5d5l_indexUK", "eq5d5l_profile", "imxrdtpost", "studyid", "dropteilklreasdesc", "mhdiagtxt", "sgothimpl", "sgopdt_cdp", "zufr_dich", "sgopyear", "examyear", "promyear", "mhvoroptxt", "zufried", "imxraxeprae")

columns_to_remove9 <- c("eq5d5l01", "eq5d5l02", "eq5d5l03", "eq5d5l04", "eq5d5l05") # "eq5d5l_indexDE", 

#' Load and Clean Data
#'
#' This function loads patient data from a `.dta` file and removes predefined unnecessary columns.
#'
#' @param file_path A string specifying the path to the `.dta` file.
#' @return A cleaned data frame.
load_and_clean_data <- function(file_path) {
  # Combine all columns to remove
  columns_to_remove <- unlist(list(
    columns_to_remove1, columns_to_remove2, columns_to_remove3, 
    columns_to_remove4, columns_to_remove5, columns_to_remove6, 
    columns_to_remove7, columns_to_remove8, columns_to_remove9
  ), use.names = FALSE)
  
  # Load the data
  df <- read_dta(file_path)
  
  # Remove specified columns
  df <- df %>% select(-all_of(columns_to_remove))
  
  return(df)
}
